### ISSUE TITLE
Allow token names and style names to be different while still in sync

### ISSUE THREAD

**Issue by danvpeterson** [tokens-studio/figma-plugin#1058]
**Is your feature request related to a problem? Please describe.**
With color styles, if I have more than one level deep of hierarchy it breaks search so that `Light / Neutral / Text / Weak` isn’t found when searching for “text weak”, or "neutral text" in the Figma color picker. It also just makes the color style picker harder to use.

Currently we name our color styles with a mix of hyphens and forward slashes, like `Light - Neutral / Text - Weak` so it’s only ever one level deep of hierarchy. This way search works reliably, and it’s easier to look at all the related colors together in the color style picker together. But of course as tokens, we want to use the actual full hierarchical grouping.

**Describe the solution you'd like**
Some way to link a token to a style with a different naming structure. Potentially just a field in the token editor for "related style name". 

Hopefully that field would auto-populate when importing styles, and could auto-complete when typing in the field by looking at all of the currently available styles. It would be awesome if it could also detect when that link has been lost (can't find the linked style) and throw up a warning of some sort.

**Describe alternatives you've considered**
You could potentially tell the tokens plugin to interpret other symbols as hierarchy as well. So it could detect both the `/` and the `-` as the same indication of grouping hierarchy (or any other symbol set by a user of the plugin). A bit less flexible in some ways than the "linked style" field, but potentially simpler.

**Comment by six7** [comment]
I think part of this will be solved by the non-local styles feature that we're working on. Basically once you have the connection set you're free to rename Styles as you please, as we already have the style connection. However when first attaching, names would need to match as otherwise we don't know how to connect styles to tokens.

Later on it would probably be good to be able to define how style names are generated (other than the current `Prefix theme name to style`. As in what you mentioned, a related style name on a token (although Token/Style connection exists on a higher theme-level, not on the individual token.

Ideally, when editing Tokens we'd also surface `sibling tokens` in other sets - showing properties that they share, e.g. this related style name.

**Comment by danvpeterson** [comment]
#145 will definitely help! Hoping that makes it into a release soon 🤞🏻. Thanks @six7, it would at least give a way to work around the problem for now. I'd still love to see a "linked style" field with auto-complete, etc. for being able to manually link them and to show the relationship fully.
