### ISSUE TITLE
View/use only mode for the plugin

### ISSUE THREAD

**Issue by danfigmatokens** [tokens-studio/figma-plugin#1245]
**Is your feature request related to a problem? Please describe.**

Most people using the plugin are purely going to be using them for consumption, without the need to edit/push/load/export/etc. The current UI is confusing for a lot of them with features they don't need.

**Describe the solution you'd like**
1. Have a way to switch the plugin to a view/consume mode. 
2. Hide edit/duplicate/delete controls for themes/tokens/sets. 
3. Remove almost the entire two bottom toolbars except the "Apply to" settings, "pull" button, and links to docs and feedback.
4. Allow combining all tokens from enabled sets into a single view (documented separately in [#1139]( https://github.com/six7/figma-tokens/issues/1139))

I think that covers everything in my mind at least. Probably some things I missed that could make it even better but this would be a fantastic start to simplify the use for folks that are not contributors.

**Comment by six7** [comment]
We're working on this on a concept level so far, we'll be changing how you apply tokens in that one: instead of showing you all the tokens you have, we'll show you something like the properties panel in figma with a way to choose tokens for each property. Effectively this reverts the mental model from 'choose token -> choose property' to 'choose property -> choose token' as this is rather how users think from Figma itself.

One question about this: I'd like to do this so it can be launched in a state where only that mode appears (using Figma's multiple launch options for plugins) without any edit permissions as you mentioned. When launching normally there'd be a new mode, however that one will still show all the other UI.

That way we get the best of both worlds:
- a read only mode of the plugin
- a different way to apply tokens, more suited to the mental model of designing, not managing.

How does that sound?

**Comment by danfigmatokens** [comment]
Oh that sounds suuuuuper interesting! Possibly the ideal situation. I'd love to have some way to switch back and forth between the modes as I will be both a consumer, and editor/manager of tokens but overall I think that could work. 

If you get to a point where you could use some early UI/UX feedback on the concept I'd love to take a look!

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/theme-switcher-for-non-ds-designers)

**Comment by SamIam4Hyma** [comment]
[Light version / view only mode of plugin](https://tokensstudio.featurebase.app/p/theme-switcher-for-non-ds-designers)
