### ISSUE TITLE
Support renaming styles, when you're not using themes.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#1382]
**Is your feature request related to a problem? Please describe.**
Currently renaming styles only works when you're using themes.

**Describe the solution you'd like**
 Add the support for renaming styles, also when you're not using themes.

**Additional context**
Initial issue: https://github.com/six7/figma-tokens/issues/1194 
Related:
https://github.com/six7/figma-tokens/issues/1381
https://github.com/six7/figma-tokens/issues/1377

**Comment by SamIam4Hyma** [comment]
@LukeFinch pretty sure this is going to be covered under #1969 #2541 so can we close?

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🚧 ❖❇️ Export styles and variables using sets (free plan) ](https://tokensstudio.featurebase.app/p/export-to-figma-using-token-sets)

**Comment by keeganedwin** [comment]
@SamIam4Hyma @six7 
This now works in both 38.9 and rc8 because upon renaming a token group you get the option to rename the style even without any themes setup:

`38.9`
![CleanShot 2024-06-25 at 16 07 08@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/87c68499-4d3a-4859-be8b-546bacd78183)

`rc8`
![CleanShot 2024-06-25 at 16 06 16@2x](https://github.com/tokens-studio/figma-plugin/assets/93133012/f40ab1a0-fa21-49dc-8a32-9d86bdb8226f)

**Comment by rbosker** [comment]
This is still an issue in rc10
https://github.com/user-attachments/assets/ae8dd5fa-9409-4ba7-bcd2-9c10935c47a1

**Comment by NuthanHyma** [comment]
Created a [new ticket](https://github.com/tokens-studio/figma-plugin/issues/3193#issue-2620801998) for this issue and closing the current one.
