### ISSUE TITLE
Token extensions

### ISSUE THREAD

**Issue by ryanbelisle** [tokens-studio/figma-plugin#1440]
## Problem
Currently, FTP doesn't have the ability to add custom data to a token.

## Solution Idea
Create a UI that allows the ability to read, add, update, delete, etc. custom data for tokens within the Edit Token modal. This is part of the [W3C draft](https://tr.designtokens.org/format/#extensions) called `$extensions`. Style Dictionary has a different approach so that should be considered as well.

- A user should be able to define any objects, arrays, strings, etc at multiple levels, within this UI to have custom data per token.
- Data is allowed to reference other data w/ same syntax. E.g. `{another.token.name.extension.data}`
- Data is saved in JSON format.
- Allow any of this data to be used as a **Documentation token** as well!

### Example
Below is an example of a color token w/ additional data I created in a previous Tokens system. All of the data here gets rendered on a website and aids to help categorize and bring forth information in different dimensions. This was created w/ Style Dictionary.

Outside of the `value` key, everything else can be considered part of an `$extension` of the token. This setup allows me to include data, in each token, around:
- WCAG compliance status and ratio
- Token names in SCSS, etc. 
- Status of token (beta, rc, released, ...)
- Version token was released in.
- Specific items I wanted to add which would add how tokens appear on the website
- etc...

```
{
  "color": {
    "palette": {
      "green": {
        "base": {
          "value": "{color.brand.green.value}",
          "rgb": "{color.brand.green.rgb}",
          "scss": "",
          "ios": "",
          "android": "",
          "sketch": "",
          "meta": {
            "name": "{color.brand.green.meta.name}",
            "description": ""
          },
          "docs": {
            "paletteCategory": "{color.brand.green.docs.paletteCategory}"
          },
          "wcag": {
            "black": {
              "aa": "{color.brand.green.wcag.black.aa}",
              "aaLarge": "{color.brand.green.wcag.black.aaLarge}",
              "aaa": "{color.brand.green.wcag.black.aaa}",
              "ratio": "{color.brand.green.wcag.black.ratio}"
            },
            "white": {
              "aa": "{color.brand.green.wcag.white.aa}",
              "aaLarge": "{color.brand.green.wcag.white.aaLarge}",
              "aaa": "{color.brand.green.wcag.white.aaa}",
              "ratio": "{color.brand.green.wcag.white.ratio}"
            }
          },
          "status": "{color.brand.green.status}",
          "release": "{color.brand.green.release}"
        },
}
```

## MVP
Maybe an initial MVP version of this could be to just have an `Extensions` textarea in the Edit Token modal which would allow users to plugin JSON as they wish and that gets stored and read? This way you don't have to build a complicated UI around it from the start.

**Comment by vnys** [comment]
My use case is that I want to remove what I consider to be redundant information from token names when working in Figma and the Tokens Studio plugin, while retaining the same information in code. I discussed it briefly with @mikekamminga some time ago, when he made me aware of [the extensions property](https://tr.designtokens.org/format/#extensions) in the design tokens spec, which I believe could be used to solve the issue.

**Scenario 1, working with the Tokens Studio plugin:** In a css variable I might want a token to be called `eds-core-color-infographics-blue-100` – but when working with the tokens in Tokens Studio the name space is superfluous for the design system designers since all the tokens are in the same namespace, the tier name is normally used as the name of the set group or the theme group (or both), and since the type is “color” there’s already a “color” heading visible. What I would like to do instead is adding the following to an extension field, either for each and every token, but ideally on a higher level to remove redundancy:

```json
"infographics": {
  "type": "color",
  "extensions": {
    "com.equinor.eds.namespace": "eds",
    "com.equinor.eds.group": "core",
    "com.equinor.eds.category": "color"
  },
  "blue-100": {
    "value": "some-color-value"
  }
}
```

_(Sometimes type and category will be the same value, other times it will not – when using dimension for spacing for example.)_

That way the information is still there, and can be added as segments in code in css-variables for example, but without taking up unnecessary space in a graphical user interface.

**Scenario 2, synchronising with Figma variables:** Similarly, when creating variables with the Tokens Studio plugin, I prefer as few groups as possible. Since I want the design system designers to add the core tokens as a library, I put them in a separate file called EDS Core Tokens – so both the namespace and the tier name is already there, and since the collection is called “color”, I don’t want to repeat that as a group name.

There might be other ways to achieve a similar result, adding abstraction sets for the sole purpose of synchronising with Figma for example, but I’m not sure how scalable that will be further down the road when there are more apps that support design tokens.

<img width="504" src="https://github.com/tokens-studio/figma-plugin/assets/2081882/7b18188f-46d8-407a-9a1e-4b33c7ab5666">

_Figma variables with simplified and verbose token structure._


<img width="318" alt="Screenshot 2023-07-03 at 08 06 17" src="https://github.com/tokens-studio/figma-plugin/assets/2081882/aad418e7-ee74-44e0-8d2e-8c5e63b1f220">

_Tokens Studio with simplified and verbose token structure._

**Comment by yapjonathan** [comment]
+1 

I have a similar use case with @vnys so having the ability to simplify the naming structure on Figma when creating them with TS will be really helpful.

![screenshot_2023-07-05_at_1 11 40_pm](https://github.com/tokens-studio/figma-plugin/assets/1426739/0c040ce8-2fbe-4c19-9750-f22a2bba8d23) Here's how it currently looks like for our component-specific tokens.

**Comment by yapjonathan** [comment]
+1 

I have a similar use case with @vnys so having the ability to simplify the naming structure on Figma when creating them with TS will be really helpful.

![screenshot_2023-07-05_at_1 11 40_pm](https://github.com/tokens-studio/figma-plugin/assets/1426739/0c040ce8-2fbe-4c19-9750-f22a2bba8d23) Here's how it currently looks like for our component-specific tokens.

**Comment by GeorgeTaveras1231** [comment]
I also have a use case.

My use case is needing to make references to other arbitrary composition tokens.

I essentially want to declare a relationship between one component and another component. 

For example, we have a navigation bar that renders a specific button variant. I want to be able to declare that relationship with tokens so to not duplicate the button variant definition for each time the button is used.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [🪙 Token metadata enhancements](https://tokensstudio.featurebase.app/p/token-metadata-enhancements)
