### ISSUE TITLE
Contents don't pass schema validation

### ISSUE THREAD

**Issue by jamesgrubb** [tokens-studio/figma-plugin#1454]
**Issue**
When I click save I get the following error "Contents don't pass schema validation"

Below is the json schema for the one token I have created.
**JSON (optional)**
```
{
  "24px": {
    "value": "24",
    "type": "borderRadius",
    "description": "Creates a “bubbly” aesthetic useful for differentiating an element from the surrounding UI."
  }
}
```
Thanks in advance.

**Comment by six7** [comment]
Can you post the whole json?

**Comment by jamesgrubb** [comment]
Hi sorry for slow reply. Full json (from inspect panel) - I’ve only set up two tokens.
{
  "24px": {
    "value": "24",
    "type": "borderRadius",
    "description": "Creates a “bubbly” aesthetic useful for differentiating an element from the surrounding UI."
  },
  "stroke-width": {
    "value": "6",
    "type": "other"
  }
}

**Comment by six7** [comment]
Sorry for the late reply. But can you give me more info? Where do you store your tokens? And how are they stored there?

**Comment by jamesgrubb** [comment]
No probs. I was following the guides to store them in a Git repository

**Comment by six7** [comment]
Can't reproduce. If you can record a video of how it happens, of the .json stored on the remote we can try to investigate further.

Please reopen once you do 🙏

**Comment by ilxsil** [comment]
Hi, I have the same issue.

When I check the JSON in [here](https://www.jsonschemavalidator.net/), it says 'No errors found. JSON validates against schema.' But the figma token plugin doesn't allow me & anybody in my team to Save Credentials and provides the 'Contents don't pass schema validation' error.

Unfortunately, I'm unable to publicly share because it's NDA work.

Could you explain what does 'Contents don't pass schema validation' means? What triggers it?

Thanks!

**Comment by jamesgrubb** [comment]
I fixed my initial issues by making sure I had created a readme.md file in the initial commit.
