### ISSUE TITLE
Apply to Selection doesn't work properly

### ISSUE THREAD

**Issue by maxarta** [tokens-studio/figma-plugin#1524]
When I have 2 themes - Light and Dark + Global, I need an ability to apply Light and Dark themes on different artboards separately. (as it was before the Swap Styles feature).

**To Reproduce**
1. Create artboards with a design on a page.
2. Apply a light theme color tokens via plugin
3. Duplicate an artboard
4. Select one of the artboards
5. Choose 'Apply to selection' in a plugin
6. Apply a dark theme
7. Dark theme will be applied on all artboards within a whole (!) figma file.

**Expected behavior**
Only the selected artboard should be applied with dark theme colors.

**Screenshots or Screencasts**
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/40794058/210784678-353831d2-5adb-422e-8b5a-9560efc1e10a.png">
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/40794058/210784760-25b38998-7763-4018-9149-837d4cc7283a.png">

**Comment by six7** [comment]
What styles do exist in that document? It sounds like both your light and dark styles are named the same?

**Comment by maxarta** [comment]
Yes. Styles named the same - that's an idea. Same tokens - different colors. It wasn't an issue before the last update. Everything is worked.

**Comment by six7** [comment]
I don't think this was introduced with the last update, but you can just disable Swap Styles in the Apply settings.

So you only have one set of styles? And you just change the value? Then even before that update it would have updated the whole doc (as it updated the styles, which are global)

**Comment by maxarta** [comment]
Disabling Swap Styles doesn't help. I record a video with the issue.

https://user-images.githubusercontent.com/40794058/211027850-63636309-8614-4b2d-b857-a988357439a7.mov

**Comment by six7** [comment]
The reason for that behavior is that you're using local styles in this document, and you do not differ between dark and light styles, both share the same style object.

When the plugin updates, it looks for styles that match the name, and in that case, it finds those. So it updates them, causing the style to change. And as Figma's styles are global, the whole page updates. This is not new behavior, it has been since the plugin supported styles.

I would advise to:
- Either create two style objects: Light, Dark (you can do so with the Themes function and the `Prefix styles with theme name` option in Settings)
- Or move styles to a shared library, but I feel in your example it'd make sense to keep styles in that document, but have two groups as mentioned above

You'd then connect styles to tokens using the Theme function (it's automatically connected when you `Create styles` with a Theme active, and depending on if you applied tokens or just styles use the Swap styles feature.

**Comment by maxarta** [comment]
Oh, Jan) you right. Now it's working good. Thanks a lot! The reason I did it is the our approach. We make layouts in a figma in the Light theme only and Dark theme will be applied automatically on FE if it needed. So I remove prefixes of color tokens 'cause I no need dark ones in a figma and to make light color tokens library reachable without opening the {theme} folder in styles)))

**Comment by six7** [comment]
Got it, I do the same! I usually have dedicated libraries for Light and Dark so the naming is not an issue. I'll close this one, feel free to reopen if there's issues.
