### ISSUE TITLE
Italic font style on typography

### ISSUE THREAD

**Issue by klevisanchez** [tokens-studio/figma-plugin#1639]
Is there a way to put an italic font style when creating typography components? So far I can only see the text decoration which does not cover italicized fonts.

**Comment by MatthiasDunker** [comment]
Maybe this is connected. When I import styles from an existing Figma file, italic font style gets recognized as `font-weight` in Token Studio. That seems strange to me.
Just tried what happens with a typo style which is bold and italic: It ends up in being imported with a `font-weight` value of `Bold Italic`.
The other way round works the same. When I create a typography composite in Token Studio with an `font-weight` value of `Bold Italic` it generates the right Figma style after **Create styles**.

So it works and is consistent, but not self-explanatory.

Is this on purpose?

**Comment by MatthiasDunker** [comment]
Although tokens should be universal, in general, I totally understand your Figma-first approach with your plugin 👍
It just feels strange when thinking about the CSS-way.
But I think for usage in web, it can be easily transformed with tools like Style Dictionary or the like.
Btw. I often transform font weights to match my opinionated way with a map (see below) so enhancing it for transforming font styling is not that big deal.

```javascript
// the map I used to date
const fontWeightMap = {
  extralight: 200,
  "extra light": 200,
  light: 300,
  regular: 400,
  semibold: 600,
  bold: 700,
};


// how it could be
const figmaFontWeightMap = {
  extralight: {
    fontWeight: 200,
    fontStyle: "normal"
  },
  "extralight italic": {
    fontWeight: 200,
    fontStyle: "italic"
  },
  "extralight oblique": {
    fontWeight: 200,
    fontStyle: "italic"
  },
  "extra light": {
    fontWeight: 200,
    fontStyle: "normal"
  },
  "extra light italic": {
    fontWeight: 200,
    fontStyle: "italic"
  },
  "extra light oblique": {
    fontWeight: 200,
    fontStyle: "italic"
  },
  // ...
};
```


> Do we ignore it?

Easiest way and ok-ish, but documenting it would help others to understand Figmas approach on this.
(Cannot be understand easily, because they offer different drop-downs for weight and style)

> Do we try to find a matching font weight?

This might be quite hard. I am not quite sure, if there is a convention for typographers to use the right naming for their variants. Back in the days, there fonts with typefaces called “oblique” e.g. — I know that this is the wrong name in this case, but would Token Studio have to handle all the different names used with a map?

> What if the font weight is already an Italic, do we ignore the font-style property?

What do you mean by this? If a typographer made a font which looks very italic-ish, but does not point it out as an italic typeface, I doubt the plugin can do anything about it.
Or do you mean a font variant which is called “italic” in the Figma drop down? Then it would fall back to a regular font weight by default, right?

**Comment by mnrendra** [comment]
Hi, @six7 I'm a frontend coder, and I agree with @MatthiasDunker that we should implement font-weight as a number (ex: 400 / 500 / 700) and need to add font-style (normal/italic) for the font style. I read from https://www.figma.com/plugin-docs/api/FontName where the FontName in Figma has a style property (ex: { family: 'Roboto', style: 'Italic' }).

So, can we add the fontStyle token in Tokens Studio? I hope we can generate CSS easily by using this additional property (font-style). Thank you!

**Comment by six7** [comment]
@mnrendra fontStyle in Figma is the font weight, they just call it differently. So it could be `fontStyle: Bold Italic`

**Comment by MatthiasDunker** [comment]
I think, there is room for improvement. But let’s face that Token Studio is a plugin for Figma and coping with Figma tokens first. I might not have enough experience since I am a web dev, only. Some designers might create designs for other target platforms which might not use CSS. So, creating a bespoken solution for CSS might clash with other target platforms.
In an ideal world, tokens should be platform agnostic and transforming tokens automatically before we know the target platform might be misleading. Maybe this could be some kind of an option. Generally, transforming tokens should be the work of [translation tools](https://design-tokens.github.io/community-group/format/#translation-tool).
Just a thought...

**Comment by SamIam4Hyma** [comment]
Proposing to close as this will be included as an expansion to typography when available on the Figma side.
