### ISSUE TITLE
Reference alias regex potentially incorrect

### ISSUE THREAD

**Issue by SorsOps** [tokens-studio/figma-plugin#1656]
**Describe the bug**
The logic for finding references does not recognize a single character reference , eg 

`$x`

due to this regex `(\$[^\s,]+\w)|({([^}]*)})`

**To Reproduce**
1. Go to `getAliasValue.test.ts`
2. Add 
```
    {
      name: 'x',
      input: 'yellow',
      value: 'yellow',
      type: TokenTypes.COLOR,
    },
    {
      name: 'xAlias',
      input: '$x',
      value: 'yellow',
      type: TokenTypes.COLOR,
    },
```

to the tokens object

3. Run the test. xAlias resolves to `$x` not `yellow`

**Expected behavior**
Single character token names resolve like their longer counterparts

**Screenshots or Screencasts**
![image](https://user-images.githubusercontent.com/80043879/222208870-ec4967a1-9a64-4700-9df7-12a16c18b0fd.png)

**Comment by six7** [comment]
does the same apply when used with the `{` notation? the `$` notation is something we probably don't want to keep supporting in the long term

**Comment by SorsOps** [comment]
`{x}` works fine.  If we can remove the `$` notation we might be able to use `$` for the start of functions similar to how apache vtl uses `#` as the start of their functions  and then we retain `{...}` for the function aliases

**Comment by six7** [comment]
I think we could work on something to automatically convert any `$` notation to `{`, however that would mean we also can't use it for functions.

**Comment by SorsOps** [comment]
@six7  Should we convert this to a future task on the backlog ?

**Comment by six7** [comment]
Yeah let's do that. I'd suggest we work on

- announce to users who use `$` notation that we're switching to `{}` notation in a few months (2 after the announcement?) and we'd encourage to switch
- automatically convert all `$` notations to `{}` notations during said communication (provide a function that does this)
- after a few months automatically convert any `$` notation we pick up to `{}`

i do not think we'll be able to use `$` for the start of functions because we have legacy users who might not have had the plugin open for 6 months or more. 

however, there could be one option, which is make it a setting.

`Use $ for references`. Default: off (so we can use it for functions), if on: will be as today.

that being said, do we need it for functions? or can we do with another character for that? because that'd solve us some trouble.

**Comment by SorsOps** [comment]
We don't need it for functions. I'm just using Apache VTL as a reference as it seems to have a similar use case, but we can use any control character for cases like this. 

I will mention that the WG has used `$` before as a prefix to other design token properties so I'd also like to avoid usage of `$` to prevent any potential clashes

**Comment by qramilq** [comment]
You can rewrite regexp 
from
`export const AliasDollarRegex = /(?:\$([^\s,]+\w))/g;`
to
`export const AliasDollarRegex =/(?:\$([^\s,]*\w))/g`

The difference from the original regular expression is the use of * instead of + after the character class [^\s,]. This makes the non-space and non-comma characters optional, allowing the pattern to match $f.

https://github.com/tokens-studio/figma-plugin/blob/next/src/constants/AliasRegex.ts#L7

**Comment by SorsOps** [comment]
I think we should look at enforcing the start name to match javascript variable name regex start patterns, ie  `[a-zA-z_]` for the initial character . The existing `[^\s,]` is a bit overly permissive in my mind.

The above regex with the *\w matches things like 

```
$$d
$\$d
$😣d
$*x
```  

which I don't think is intentional.

I will say however that internationalization needs to be considered here as well. If we want people to write in their native language, we would need to support

```
$いてっ
$Götterdämmerung
``

etc. To note above is that we do currently support `$Götterdämmerung` as it terminates with an allowable ascii character , but not `$いてっ` . Assuming we have existing international clients `(?:\$([a-zA-z_]\w*))` would break their existing implementation

**Comment by SamIam4Hyma** [comment]
@six7 curious if we can close this one assuming these issues will be addressed with the DTCG WCAG work with these characters, but I might not be understanding it fully.
