### ISSUE TITLE
Tokens get disconnected when renaming 

### ISSUE THREAD

**Issue by PC-Miele** [tokens-studio/figma-plugin#1781]
**Describe the bug**
One ‘bug’ I discovered is that tokens disconnect after renaming if you don’t select them upfront. Documentation tokens get disconnected as well.

**To Reproduce**
1. Apply a token to a frame / or set an documentation token like name
2. Rename this specific token without selecting anything.
3. Check if the token is still connected.

**Expected behavior**
Renamed tokens should not get disconnected after renaming.

**Screenshots or Screencasts**
https://cloud.cleiren.nl/TsdWndXTjrSp0rKKx174 
https://user-images.githubusercontent.com/108468049/229297884-f8723378-7f4d-4840-b24c-433c9c2d929d.mp4

**Comment by six7** [comment]
This is expected. The popup that appears after renaming a token is one we've implemented to solve the problem that tokens get disconnected.

The alternative to asking the user where to rename their tokens would be to scan the whole document, and remap any tokens that used the old name, with the new name. This is unfortunately an operation that takes a while, so we don't want users to have to wait a long time just because they renamed a token (in large documents updating all references can take a while!)

Inclined to close this for now, let me know if you think this is a wrong assumption

**Comment by SamIam4Hyma** [comment]
closing this issue until more info is provided.
