### ISSUE TITLE
tokenName alignment and tokenValue width in inspect

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1782]
**Is your feature request related to a problem? Please describe.**
The inspect panel does not have an organised way of displaying the `tokenNames & Values` - user is having to _haphazardly_ scan the section to identify the tokens

![image](https://user-images.githubusercontent.com/93133012/229468644-1a7f4afb-48ae-407b-a011-d4b961196420.png)

**Proposal:**
1. The `tokenValues` container should have the same width and not move into the next _line_ like with `4,8` of the `label` token
2. This should then result in the `tokenNames` being aligned left - on the same `vertical line`

**Comment by six7** [comment]
I think we should
- force a max width of the one we have today
- Use the same width for the color swatches (just the container, not the actual swatch) so that also colors being and the same line
- Same for `none` value tokens and any other tokens that use an icon instead of a text
- Truncate each value preview so the text doesnt wrap, is on 1 line (no ..., just cap the text)
- Have a tooltip for each of those that shows the full token (the same tooltip we show when you hover a token in the Tokens tab)

**Comment by six7** [comment]
I think we should
- force a max width of the one we have today
- Use the same width for the color swatches (just the container, not the actual swatch) so that also colors being and the same line
- Same for `none` value tokens and any other tokens that use an icon instead of a text
- Truncate each value preview so the text doesnt wrap, is on 1 line (no ..., just cap the text)
- Have a tooltip for each of those that shows the full token (the same tooltip we show when you hover a token in the Tokens tab)

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Here's the URL to the featurebase post that is linked to this ticket: https://tokensstudio.featurebase.app/p/enhance-inspect-page-in-the-plugin
