### ISSUE TITLE
Allow `description` in token groups

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1811]
The DTCG format specifies that you can have a `description` property on token groups. Let's allow that.

### Add an entry point to edit token groups in the UI
- We currently allow users to `Rename` a token group. Let's rename that to `Edit` which opens a modal allowing users to edit the name, description and type of a token group (we already support the type property, but we currently only let users add it in JSON. Let's add it in the UI as well). 

- Add type input
- Add description textarea
- Add Cancel button
- Add Save button

### Display the token description in the UI (when present)
- If there's a group description present, display it to the right of the group name.
- The group description should take up the remaining space of the row, but not be multi-line
- The group name should not be multi-line and should not shrink if the description is longer.
- If something would be truncated, it should be the description.

![Image](https://user-images.githubusercontent.com/4548309/227805522-7c9bbc81-88c6-422a-b686-9f3ef6d754eb.png)

![Image](https://user-images.githubusercontent.com/4548309/232206574-14a909fd-3a04-4a62-a35e-a3a756f843b6.png)

**Comment by SamIam4Hyma** [comment]
@six7 while reviewing this for V2 planning I have some questions/unknowns: 

1. Where does this information appear in the process / why would I bother to populate it / who cares about this metadata?
- Today, in the plugin, we group by type, but in the future, we can group by intuitive measures, so is this to support that? 
2. How does this appear in the JSON? Is it different if I am switching between the new DTCG and legacy token formats? 
3. What happens when I have several nested groups? (ex: actions.cta-buttons.brand-tier1.icon.size)
4. When the description is added and truncated, how can I see the full name in the plugin? 
5. When token group type is assigned, does that change the token type? 
6. On token group type, you have copy that says "unless otherwise specified" - what does that mean? 
7. What impact does this have on transformation/using in code if any?

**Comment by SamIam4Hyma** [comment]
@six7 are we moving from V2 to a later release? can you please adjust the label for me to reflect what you are thinking?

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ DTCG W3C | Token Group Metadata - Description and Type](https://tokensstudio.featurebase.app/p/token-group-metadata-description-and-type)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[❇️ DTCG W3C | Token Group Metadata - Description and Type](https://tokensstudio.featurebase.app/p/token-group-metadata-description-and-type)

**Comment by SamIam4Hyma** [comment]
closing as not planned for now. It is linked t[o this Featurebase post](https://feedback.tokens.studio/p/token-group-metadata-description-and-type) so we can reopen when we are ready.
