### ISSUE TITLE
Allow Order of Operations in Spacing Type Reference using Brackets/Curly-Brackets

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#1895]
**Is your feature request related to a problem? Please describe.**
Currently, users can use math in spacing type reference by referencing two or more tokens. However, it would be beneficial to allow users to use math within brackets/curly-brackets that reference another token. 

**Describe the solution you'd like**
If the token being referenced within the brackets/curly-brackets is 4px, and is then multiplied by (*2) within the brackets/curly-brackets, it would result in 8px. This value is then multiplied with the referenced token outside the brackets/curly-brackets, which is also 4px. The final result would be 32px, which is the product of the two multiplied values.

![image (5)](https://github.com/tokens-studio/figma-plugin/assets/93133012/91df199c-9adb-4652-85af-c131a447c97b)

**Comment by six7** [comment]
I'd be interested in the opinions of @mikekamminga, @SorsOps and @jorenbroekema on that one given I'm not sure we want to go even further on our string-math implementation, as this would further complicate output and transforms.

From a syntax perspective I don't agree with putting stuff inside `{}`. This should be reserved for references. From a perspective of letting you put math inside tokens that use multi-value, I could see some value. But I'd be hesitant on that one as I think math needs to be solved in a different, more elegant way.

**Comment by mikekamminga** [comment]
For me, multi-value I would as user expect that every value works like any other value, so I would expect I could use math. From a syntax pov I'd say `({value1}*2) {value2} 8px ({value1} + {value2})` should be perfectly valid imo. But if we have challenges in handling this, I'm happy to not have this feature.

**Comment by jorenbroekema** [comment]
I'm pretty sure in sd-transforms, it is even possible to do `{value1}*2 {value2} 8px {value1} + {value2}`, since I interpolate math operators (+-/* etc.) and then use some crazy heuristics to determine that the value before and after a math operator must belong to a single expression. It extends even to stuff like `{value1} * 2 * 10 * 8 {value2} 8px {value1} + {value2} - {value3}`. I'm not entirely sure how it behaves with `( )` parentheses, I do have one test for this use case `expect(checkAndEvaluateMath('(15 + 20 - 17 * 8 / 3) * 7px')).to.equal('-72.333px');` but not sure how far that can be stretched. Here's the test file https://github.com/tokens-studio/sd-transforms/blob/main/test/spec/checkAndEvaluateMath.spec.ts to see what's supported in sd-transforms

My opinion however is that this code for splitting multi-value expressions into single expressions is probably in the top 5 most awful code I have written to date, and I expect it to be rather fragile. It's definitely not maintainable code and you will curse me if you ever have to fix a bug in it. So my preference is that we don't extend this "math string interpolation" thing with more features, and that we make concrete plans to ditch what we have currently for something that properly parses such expressions (I believe Andrew is looking into this right?)

**Comment by SamIam4Hyma** [comment]
@LukeFinch please take a look at close/archive or label accordingly. This solution doesn't appear to be viable but my understanding is limited.

**Comment by jorenbroekema** [comment]
3/4 year since my last message and yeah please archive this, I think this feature would be a bug paradise and a maintenance hell also makes tokens really hard to reason about and to debug
