### ISSUE TITLE
[Performance]: Cache alias evaluation

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#1900]
We should be caching these alias values when they are evaluated and using something like the AST to determine if a value needs to be re-calculated if we know the references haven't changed. Easiest and dirtiest way would be to assign an id to the values and just use that to determine if a token we need to for evaluation has changed.

**Comment by SorsOps** [comment]
This is related to #2056 

If we can create a resolver cache that handles the references as we switch between sets we can invalidate this cache by checking if a references id is different to attempt to short circuit lookup logic

Due to this being dependent on #2056, this should likely be delayed to next sprint if its not completed early
