### ISSUE TITLE
Replace style with variables

### ISSUE THREAD

**Issue by XavierVilars** [tokens-studio/figma-plugin#1983]
**Is your feature request related to a problem? Please describe.**
Until today I was using as everyone here styles in all my components. But I want to use variables now. It's tousand of tokens used in mutiple components every where. And I don't want to do it manually.

**Describe the solution you'd like**
So it's cool to be able to export variables but how can I swap my styles with variables using Token Studio ?

**Comment by bewarai** [comment]
Yeah, have the same question as well. I found out by removing styles and remapping them works. But that's still a lot of manual labour. Any way of having this faster done? Or maybe I am doing it wrongly as well?

**Comment by six7** [comment]
in the latest release once you have connected your tokens to variables you are able to just apply and we will automatically apply the variable. important: you'll need to connect your variables to tokens once more, by just pressing `Create variables` in the footer (or `Attach variable` in the Manage themes dialog).

Then it's just a matter of pressing "Apply to.." and we will apply the variable instead of style or hex.
