### ISSUE TITLE
Ability to Use Modifiers with Box Shadows for Semantic Palette Integration

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2141]
**Is your feature request related to a problem? Please describe.**
This feature would enable the user to create a standard elevation pattern that can be used to generate palette-specific shadows, allowing for color-matched shadows to integrate with a semantic palette.

**Use Case Scenario:**
Currently, while using box shadows, the user is limited to static values for the shadow properties (e.g., color, size, blur, spread). However, they would like to take advantage of a semantic palette that defines a range of colors representing various themes and states within my application. By introducing modifiers for box shadows, they can generate headless shadows that can easily adapt to these semantic colors.

**Describe the solution you'd like**
Allow for the implementation of the ability to use modifiers with box shadows.

**Comment by chriskerr-performio** [comment]
@keeganedwin This sums it up well.

Essentially I want to be able to define the x, y, blur & spread independently (each value being a numeric should also be able to use an alias as well as a value)

I then want to combine this abstract concept of elevation (basically the shadow intensity and direction) and then create a box-shadow token based on:

a) a color token (including alpha layers)
b) optionally an opacity token (personally I have my colored alpha layers pre-defined rather than dynamically in core color tokens so that I can use Variables properly blending alphas in from 2 token values prevents the variable from retaining it's link to the core color or opacity token). however this might be useful to be able to apply either a color with alpha, or a color + opacity
c) The elevation token you want

The main use case for this is to consistently use light and elevation. but be able to colorise them against the colors set in a white-label multi-brand DS which uses brand-specific seed colors to drive the entire color system

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
https://tokensstudio.featurebase.app/p/enhanced-functionality-for-boxshadow-tokens-greater-effects-in-figma

**Comment by UdayHyma** [comment]
Added to FeatureBase Roadmap : [🎨 Expand functionality of color modifiers](https://tokensstudio.featurebase.app/p/expand-functionality-of-color-modifiers)
