### ISSUE TITLE
It's still ignoring first part of token name for Styles

### ISSUE THREAD

**Issue by sannevangool** [tokens-studio/figma-plugin#2264]
**Describe the bug**
We experimented a bit with tokens, but now we don't see the frist part of the token name for styles back in our JSON. We don't have the checkbox filled in?

**To Reproduce**
1. Go to 'JSON'

**Expected behavior**
Seeing color, border radius, spacing in JSON as groups

**Screenshots or Screencasts**
<img width="525" alt="Scherm­afbeelding 2023-09-25 om 15 30 24" src="https://github.com/tokens-studio/figma-plugin/assets/138762041/18c8d540-c462-4c78-ab4c-4951ffa585d4">
![image](https://github.com/tokens-studio/figma-plugin/assets/138762041/2371af6c-63e0-4aa8-aeeb-e745f33cf339)

**Comment by six7** [comment]
That feature basically means "When you create styles, ignore the first part of a token name", as in when you have the following tokens:

```
colors: {
  gray: {
    500: {},
    600: {},
    700: {},
  }
}
```

And you create styles, the styles will be named `gray/500, gray/600, gray/700` instead of `colors/gray/500, colors/gray/600, ..`

I think you're after something else here? In your case, it's best to name the tokens how you want them to be named.

**Comment by sannevangool** [comment]
Yes, I know it's broken. The toggle does not work for our plugin..

**Comment by sannevangool** [comment]
Any solutions or ideas for this problem?

**Comment by six7** [comment]
I'd say the solution I proposed further above works for you. Any thoughts on why not?
