### ISSUE TITLE
Modifier for Typography Reference Mode

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2310]
**Is your feature request related to a problem? Please describe.**
A feature that allows adding modifiers to the "reference" mode in typography. Currently, when defining a typography token like "base-paragraph," it would be helpful to have the ability to create a style like a "bold paragraph" by simply adding a modifier to the existing reference token.

**Used-case:**
If a user has a typography token called "base-paragraph" that defines various properties such as font family, font size, line height, etc. Instead of duplicating the entire token and specifying a different font-weight for a "bold paragraph," it would be more efficient to add a modifier to the reference token.

**Describe the solution you'd like**

1. Define the "base-paragraph" typography token with all the desired properties, excluding font-weight.
2. Create a modifier, such as "bold," which can be linked to the "base-paragraph" token.
3. Specify the desired font-weight for the "bold paragraph" using the modifier while inheriting all other properties from the "base-paragraph" token.

**Comment by straef** [comment]
i came here to make this feature request (since #2292 is not considered a bug). please prioritize this. one of your recent releases literally broke all of my typography tokens. now instead of cascading values through aliases i have to connect every token to root values. this means any changes would need to be made in dozens of locations, increasing errors and maintenance effort.

**Comment by denis-strong** [comment]
This is also related to Composition 2.0?

**Comment by UdayHyma** [comment]
[Migrated to Featurebase](https://tokensstudio.featurebase.app/p/greenheart-v2-quality-of-life-enhancements)
