### ISSUE TITLE
Show Tokens in Dev Mode even when Styles or Variables are Applied

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2319]
**Is your feature request related to a problem? Please describe.**
We currently only display applied tokens in Dev mode but users also have styles & variables attached to their tokens.

**Describe the solution you'd like**
Would it be also be possible to display tokens when a user applies style or variable only but that are attached to their corresponding tokens? 

**Definition of done**
When a style or a variable which is linked to a token is applied on a layer. Show the token applied in the Dev mode.

**Comment by robin-deriv** [comment]
Looking forward to this feature release. Thanks

**Comment by esthercheran** [comment]
@robin-deriv In case a style or variable is applied, in the dev mode we can already see that information. In case a style or variable that is linked to a token is applied, would you like to see the token name under the Tokens Studio section? Just for my curiosity, in your workflow would the developers pick up the token name and not the variable or style name that is applied?

**Comment by robin-deriv** [comment]
@esthercheran If we select styles from figma properties menu, we can not able to see the token name in Dev Mode. However, our tokens and figma styles naming are fully same and we transfer those styles from TS plugin. So both are same but still if our designer choose style from figma they are unable to see in dev mode. It would be great, if they see assigned token in dev mode in this case. 

But, Later I realize, still devlopers can see assigned tokens using token studio inspect section. Currently our develoeprs working using inspect instead of dev mode. So it will be a additional feature.

**Comment by esthercheran** [comment]
Thank you for explaining the use case @robin-deriv !
We can explore to add the token name in Dev mode, in case a style or variable linked to a token is applied on a layer.

**Comment by LukeFinch** [comment]
This request has been moved to our new feedback tool. Go check out https://tokensstudio.featurebase.app/ to create a free account. You can upvote and comment on existing posts, make a new request, and subscribe to be notified when requests move into our roadmap.

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [👨‍💻 Enhance data in Dev Mode](https://tokensstudio.featurebase.app/p/enhance-data-in-dev-mode)
