### ISSUE TITLE
Unable To Apply Max-width Tokens On Component Instances

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2426]
**Describe the bug**
When applying the ﻿max-width token directly to an instance, it does not get applied/override. The ﻿max-width override however works as expected when applied to the master component.

> This is quite impactful for us because it means not only are we  unable to see proper max-widths on the instances with theme/set overrides, but if a designer accidentally types in a max-width value on the instance, it sticks i.e. the tokenized value from the master never resets it back to what it should be.

This also seems similar to #2270 

**To Reproduce**
1. Select main component
2. Check `Test` set
3. See change
4. Uncheck `Test` set
5. Select component instance
6. Check `Test` set
7. See error

**Expected behavior**
Max/min-width tokens should also override on instances.

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/68d3ff55-3683-425c-8d84-ac1e0fc87094

**Figma file (optional)**
[Test board](https://www.figma.com/file/egeTaCchJqdTFfoJJK8vIZ/Max-Width-issue-on-instance?type=design&node-id=11-71&mode=design&t=xGdM0dZLMVs0hJun-4)

**Comment by oorhon70** [comment]
For some reason, my original screencast was replaced with another one in the ticket description, which seems to be a bit misleading in terms of describing the issue. @robinhoodie0823 I just wanted you to see the original too, hoping that it'll help with verifying the fix.

https://github.com/tokens-studio/figma-plugin/assets/94029680/0db47aba-82de-4a17-80d0-c657a6302927

Thanks, –oo

**Comment by six7** [comment]
The problem here lies in the fact that Figma cannot update maxWidth or minWidth component instances. Even if you tried doing it in Figma itself, without the help of a plugin, you cannot do it.

https://github.com/tokens-studio/figma-plugin/assets/4548309/37054f79-e9b9-462a-acd0-cfd72e0a2328

I'm closing this, as there's nothing we can do here unfortunately. It's just how Figma works. If you feel this is done in error, feel free to comment (maybe i misunderstood)

**Comment by oorhon70** [comment]
@six7 yes, it makes sense that Figma cannot override the max-width of the nested element. But the instance itself should follow the max-width token, because Figma allows for it. In your example, if you select the instance "Rectangle 2", and apply a max-width token, you'll see that it doesn't work.

https://github.com/tokens-studio/figma-plugin/assets/94029680/4c256e1f-eead-4214-9b5c-3ec8f6c3a87b

Can we reopen this ticket?

**Comment by six7** [comment]
Oh that makes sense, thanks for highlighting that part 👍 Reopened the issue

**Comment by six7** [comment]
Will be fixed in 2.0

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🐛 V2 Bug Fixes](https://tokensstudio.featurebase.app/p/v2-bug-fixes)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap-	[🐛 V2 Bug Fixes](https://tokensstudio.featurebase.app/p/v2-bug-fixes)

**Comment by keeganedwin** [comment]
Reopening as this issue is still present in RC7 (@cuserox). Here's the [test file](https://www.figma.com/design/L2Ghy8ONZE17cEYplHb3ZE/Untitled?node-id=17-1003&t=8pGgADzSzh7H8bwV-4) with steps mentioned on how to reproduce.

Here's also a video of the bug:
https://github.com/tokens-studio/figma-plugin/assets/93133012/99862b59-4a02-4b13-bc6b-dc9e3e65c533
