### ISSUE TITLE
Inner Shadow Property Is Retained After Unapplying Token

### ISSUE THREAD

**Issue by NuthanHyma** [tokens-studio/figma-plugin#2454]
**Describe the bug**

In the `box shadow` type, when the token is applied as an `inner shadow` property and then deselected, the property is not removed from `Figma` - the `inner shadow` stays on the frame. This does however work for the `dropshadow.`

**To Reproduce**
1. Navigate to global set >Box shadow 
2. apply the `inner shadow` property 
3. Then deselect the `inner shadow` property 
4. The property stays and does not get deselected.

**Expected behavior**
When the `inner shadow` property is deselected, the `inner shadow` property should also be cleared. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/140593995/f4cb5a67-89ba-4593-9a1d-a8579da8ffee

**Figma file (optional)**
[Test](https://www.figma.com/file/DT3hBiDFhX82vDaHkQaUTF/issue-%232454?type=design&node-id=0%3A1&mode=design&t=4BIW1sivC4rC1nKE-1)

**Comment by SamIam4Hyma** [comment]
I can confirm this is consistent in the V2 build. I am changing this to a `💡request` because if you look at the label for `remove token` we have about 5 issues where folks have different desires for this functionality. Some want the property to persist when the token is removed, others want the property removed, some think it should be a setting. 

In migrating this to featurebase we can get a better pulse check.

**Comment by SamIam4Hyma** [comment]
Migrated to featurebase https://tokensstudio.featurebase.app/p/removing-a-token-removes-the-design-property-in-figma if you want to upvote (:

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap : [💡Removing a token removes the design property in figma](https://tokensstudio.featurebase.app/p/removing-a-token-removes-the-design-property-in-figma)
