### ISSUE TITLE
When Importing New Variables Does Not Update Token Value

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2529]
**Describe the bug**
When a number variable's value is changed and is to be imported (previously imported) into TS, the token's value isn't updated until unless the active set is `checked` and `unchecked`.

**To Reproduce**
Instructions are long, test file has steps to reproduce.

**Expected behavior**
Token value should update once the new value is imported.

**Figma file (optional)**
[Test File](https://www.figma.com/file/cjx26rWEdoOROzYfaXGrvK/Empty?type=design&node-id=317-13&mode=design&t=z6NsIUVB1UCjcRQR-4)

**Comment by SamIam4Hyma** [comment]
Added to Featurebase Roadmap as a known issue to test and track with V2 beta testers -	[❖ 🪄 Sync variables and styles is now Export to Figma](https://tokensstudio.featurebase.app/p/sync-styles-and-variables-is-now-export-to-figma)

**Comment by SamIam4Hyma** [comment]
@keeganedwin FYI this issue only exists if you haven't hooked up the variables to a theme group and theme (pro). Once you do that and the tokens are connected, you can update the variables and run the import and the values will update.

**Comment by keeganedwin** [comment]
@SamIam4Hyma @six7 this bug is still present in rc9. Even if themes are setup after importing variables and you change a value in figma then import this change, it only updates if you either switch themes or switch between sets
[Video](https://github.com/tokens-studio/figma-plugin/assets/93133012/704e99cf-e8a6-4306-94cd-3e1d07199676)

**Comment by cuserox** [comment]
I have raised a PR to fix when **a Figma Variable value is updated & imported into the plugin, the token value is instantly reflected** 🌟 

Cross posting here, as there are another two ❓ scenarios ❓ I'm not sure what the behaviour should be, when variables are imported into the plugin. Perhaps worth refining?

CC @SamIam4Hyma @keeganedwin @six7 

| Action | Current Behaviour | Expectation | 
| ----- | ----- | ----- |
| What happens when a Figma Variable is renamed (i.e. `test-color` to `test-color-new`) | A new token is created with the name `test-color-new` | ❓  | 
| What happens when a Figma Variable is deleted | There is no change in the tokens | ❓  |

**Comment by cuserox** [comment]
This is now merged into the v2 branch 🎉 

CC @SamIam4Hyma @keeganedwin will be available to test on the next fix 😄
