### ISSUE TITLE
[2.0]: Trying to use Second screen fails with 401 unauthorized

### ISSUE THREAD

**Issue by six7** [tokens-studio/figma-plugin#2739]
We seem to have changed something about the implementation of Second screen, it now seems to fail with 401 unauthorized.

To reproduce
- Click on `Second screen` icon in the top right
- Try to create an account or login

Possible point of entry: packages/tokens-studio-for-figma/src/supabase.ts

Might be related to React 18 ?

![Image](https://github.com/tokens-studio/figma-plugin/assets/4548309/a2beab81-b2ea-4378-aa1d-ed21c481d313)

**Comment by cuserox** [comment]
## Fixed _locally_

Was able to reproduce the **401** error, where _"no `apiKey` was found in the request"_
<img width="1523" alt="Screenshot 2024-05-23 at 17 27 28" src="https://github.com/tokens-studio/figma-plugin/assets/114073780/fc2d6150-e6f9-456e-bdb4-64e25a212e3d">

✨ Fixed by adding the `SUPABASE_ANON_KEY` (accessing + unwrapping vault secret) on the local `.env` file

**Comment by cuserox** [comment]
# The current / long term fix

All releases should be triggered through the GH actions (https://github.com/tokens-studio/figma-plugin/actions/workflows/nightly.yml) to avoid missing environment variables and provide correct tracking parameters (i.e. Sentry)

## Follow-up

Audit all environment variables and ensure they are injected through the build (instead of having to recreate `.env.*` files) https://github.com/tokens-studio/figma-plugin/issues/2788

**Comment by six7** [comment]
Confirming this is closed with the addition of env variables
