### ISSUE TITLE
'No Variables Created' With Beta rc7

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#2828]
**Describe the bug**
Some users have raised the issue of not being able to create variables with Figma displaying 'No Variables Created'. The variables are however still created, but they're created as blanks. Even if you reconfigure the themes (which is not actually required) they are created as blanks after this. 

**NOTE**
I have tested this in the production/live build with the same 'themes' setup and it just created variables as expected.

**To Reproduce**
1. Have token set that with more the 1 theme-group
2. Create variables
3. See error

**Expected behavior**
Variables should just be created as it did with rc6 and prod 1.38.9. 

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/93133012/b0a26f8a-0ace-4b0a-8e94-961ce0694f80

**Comment by cuserox** [comment]
🔢 Please note: numbers on the toast are now correct 😄 https://github.com/tokens-studio/figma-plugin/pull/2840

**Comment by cuserox** [comment]
🧐 Potentially a misconfiguration from the user's side, instead of a bug. Speaking with @keeganedwin & @six7 to understand if this is the way forwards, to educate on how to avoid Figma variables that when created are empty or missing alias references. 

Advice to users when managing themes, before exporting them:

- In the **Sets** tab: ensure the sets used in the theme are “Enabled” and all the other sets needed to resolve any aliases are marked as “Reference Only”
- In the **Styles & Variables** tab: select all variables and detach them all

Remember to click on **Save theme**. Export them and see ✨

**Comment by cuserox** [comment]
⏳ Messaged the community with advice ([**thread here**](https://tokens-studio.slack.com/archives/C073SSG7DC7/p1718618779750349?thread_ts=1717694356.906189&cid=C073SSG7DC7)) on how to mitigate this 'bug'. Awaiting for responses and more information, in case it is a bug vs a misconfiguration of themes.

**Comment by six7** [comment]
Let's close this and reopen if the issue comes up again.
