### ISSUE TITLE
Value in the plugin not properly updating, when importing Styles or Variables.

### ISSUE THREAD

**Issue by rbosker** [tokens-studio/figma-plugin#2930]
**Describe the bug**
Value of a token in the plugin is not properly updating, when importing Styles or Variables. The plugins shows that there are differences, but that doesn't reflect in the plugin. Once you for example toggle theme, make another change or reopen the plugin, the new imported value is visible afterwards.
This is not only the color swatch for example, but also if you open the token, the old value is still present.
Note: issue is present in [V 2.0-rc8] and 1.38.9

**To Reproduce**
1. Create a variable/style
2. Import style/variable in the plugin
3. Change the value of the style/variable and import that again in the plugin.

**Expected behavior**
I expect for the changes to be visible instantly, without having to interact further with the plugin.

**Screenshots or Screencasts**
https://github.com/tokens-studio/figma-plugin/assets/109062656/e0a3b737-2671-47cf-84e5-d646a52d086c

**Comment by keeganedwin** [comment]
I think I missed this ticket when creating [When Importing New Variables Does Not Update Token Value #2529](https://github.com/tokens-studio/figma-plugin/issues/2529), but this has been fixed as of `rc10`. I don't know about the styles though.

**Comment by akshay-gupta7** [comment]
This is working fine in RC11 for styles as well. @keeganedwin and myself tested it out. Closing this issue.
However what we also noticed is:
"When we create a style and import it and a new token is created. Then, if we change the style properties and import it again, it is working as expected. However, if we change the name of the style or even move the style to another folder, and import styles again in the plugin, a new token is created instead of updating the existing token's name.
Not sure if we already have had a discussion around this, but we can explore how to keep the style and the token it created always linked regardless of name or folder change."
CC: @six7
