### ISSUE TITLE
Styles aren't Applied with Prefix Styles with Theme name

### ISSUE THREAD

**Issue by keeganedwin** [tokens-studio/figma-plugin#3145]
**Describe the bug**
Currently when using non-local libraries for styles with the following setup and applying tokens in **File 3**, `hex-values` instead of styles are applied if and when the `Global`, `Semantics` and `Themes` (multiple themes) are selected. If I however `deselect` globals and semantics and **ONLY** have Themes selected, the plugin applies the style:

**File 1:** Export Global Styles
- Push changes to the provider
- Publish the library

**File 2:** Enable the global library
- Export semantics
- Push changes to the provider
- Publish the library

**File 3:** Enable Global & Semantics
- Export themes
- Push changes to the provider
- Publish the library

This bug is present in the library with the exported styles as well as an external library that has all three library enabled. 

**Insight from @six7 -**
> This seems to be related to the prefix styles with first part of token name setting. There were a few changes made to this recently which seems to be the cause of this error. We basically seem to only use the first `active theme` name to detect the name, which is wrong in this case.

**Expected behavior**
I think we should just go back to the previous functionality where regardless of how may themes are selected the plugin applies the styles of the `Selected`  theme of each theme-group.

**Screenshots or Screencasts**
[Recording](https://github.com/user-attachments/assets/6d213375-a5f3-4662-9212-b619992a8fce)

**Figma file (optional)**
I already have the files for this setup and can share the tokens if required.

**Comment by six7** [comment]
Changed the title to reflect that this has nothing to do with non-local styles. This has to do with `Prefix styles with theme name` - if multiple themes exist we seem to always only use the first theme name due to https://github.com/tokens-studio/figma-plugin/blob/main/packages/tokens-studio-for-figma/src/plugin/TokenValueRetriever.ts#L22-L31 as well as https://github.com/tokens-studio/figma-plugin/blob/cddfb5bae173a123f62c181f7ecb62495f04ff61/packages/tokens-studio-for-figma/src/plugin/asyncMessageHandlers/getThemeReferences.ts#L20 where we seem to take the *first* theme name, which *cannot* work if you have multiple themes.

**Comment by keeganedwin** [comment]
Just adding that this is also present with exported typography styles in the `same file`. If I apply a typography token from the `Bio/Light` set it applies the style. As soon as I select `Headless` or `Bio` core it breaks and applies raw-values

![CleanShot 2024-09-19 at 19 00 57@2x](https://github.com/user-attachments/assets/a3528408-8766-4873-ac82-a6989c043c01)
