### ISSUE TITLE
Inconsistent file changes when creating PRs from Tokens Studio with Bitbucket

### ISSUE THREAD

**Issue by UdayHyma** [tokens-studio/figma-plugin#3187]
**Describe the bug**
When creating a Pull Request (PR) from a branch in Tokens Studio with Bitbucket, the user sees 44 files changed, including deletions and incorrect additions, even though the only change made was in a single file (tokens.json). The file changes shown in the PR are incorrect, as the tokens.json file is being flagged as completely new. 
**To Reproduce**
1. Make sure in single file tokens.json
2. Convert to W3C format 
3. Click Create pull request
4. The number of files changed shows wrong and pulls incorrectly

**Expected behavior**
 Only the changes made to the tokens.json file should appear in the PR. No additional files should be changed, and there should be no deletions unless explicitly made by the user.

**Screenshots or Screencasts**

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

**Comment by withinsight** [comment]
Does Tokens Studio do anything to detect which branch is the default branch in Bitbucket repos? 

I'm thinking this is perhaps caused because our "Main branch" is set to `default` in Bitbucket. If Tokens Studio isn't detecting the default branch, and its starting with `main` or `master`, that might cause the issue.

Even though I manually selected `develop` as the branch to start with, it feels like Tokens Studio is still using `main` or `master`.

**Comment by six7** [comment]
@rbosker is this still an issue? i thought the last release might have addressed this, but unsure

**Comment by rbosker** [comment]
@withinsight [the plugin is detecting the default branch, that you enter in the plugin.](https://docs.tokens.studio/token-storage-and-sync/sync-provider-bitbucket#5-branch) 

@six7 I can't reproduce this anymore after the release of [this PR](https://github.com/tokens-studio/figma-plugin/commit/23caccded5c08bc9ea5e730e9e0d9017cf626cfc). @UdayHyma can you also double check to be sure?

**Comment by six7** [comment]
I'll close, reopen when it keeps appearing
