### ISSUE TITLE
[Git Sync]: Bitbucket Support

### ISSUE THREAD

**Issue by jared-christensen** [tokens-studio/figma-plugin#380]
Any plans to add bitbucket?

**Comment by six7** [comment]
Not so far, but if there's serious interest from teams then definitely!

**Comment by jared-christensen** [comment]
Thanks for the response! What an awesome tool you have created! We just set it up so our designs can export design tokens from Figma and then that automatically kick off a build that starts style dictionary and deploys it to an AWS S3 bucket. It's an awesome workflow!

**Comment by TheeMattOliver** [comment]
Lots of teams that have to use Bitbucket in work projects, would very much love to see this.

**Comment by six7** [comment]
Quick update on this: We kind of hit a roadblock with bitbucket as they don't seem to have a concept of personal access tokens, instead requiring OAuth.

**Comment by TheeMattOliver** [comment]
Yeah, that sounds about right. So what's the right approach here? Fork of figma-tokens or something? I seriously doubt Atlassian will be adding support for personal access tokens to Bitbucket. I would love to be wrong about that.

**Comment by six7** [comment]
OAuth isn't impossible for Figma plugins, it's just adding a step for us which we'll get to eventually. Ideally users can authenticate with all git providers via OAuth, so definitely something we'll want to do.

**Comment by qmdev** [comment]
> Not so far, but if there's serious interest from teams then definitely!

I just want to add my support to this.
I work for a large content marketing agency on the webdevelopment department.
All our projects are kept in Bitbucket.
The team is currently working towards a "figma-tokens to style-dictionary to code" implementation as the team grows.
Bitbucket support would mean that our tokens could be pushed right into the repository of the website.

So I hereby show "Serious interest" in this implementation. 😄
Keep up the great work Six7

**Comment by namyarxam** [comment]
Hoping for an update on this!

**Comment by firebait** [comment]
This would be fantastic! 
Wonder why don't you have some generic git support with an SSH public key. That way there is platform dependency, it's just git.

**Comment by jvdl** [comment]
>  Quick update on this: We kind of hit a roadblock with bitbucket as they don't seem to have a concept of personal access tokens, instead requiring OAuth.

Hi Jan, former Bitbucket Server frontend dev here, and current user of Bitbucket Cloud. Both Bitbucket Server and Cloud support personal access tokens for Git and REST operations. In Bitbucket Cloud they are called [App passwords](https://developer.atlassian.com/cloud/bitbucket/rest/intro/#app-passwords). I see that  #950 adds support for Bitbucket Cloud <3 so y'all have this covered :-)

We're loving this plugin, and I'm sure folks that use Bitbucket Server would love it if they're covered too. If you did also want to add support for Bitbucket Server, Personal Access Tokens are called [HTTP access tokens from 7.18 onward](https://confluence.atlassian.com/bitbucketserver/http-access-tokens-939515499.html) and [Personal access tokens in Bitbucket Server 5.5—7.17](https://confluence.atlassian.com/bitbucketserver0717/personal-access-tokens-1087535496.html) 

Thanks for all the hard work and effort!

**Comment by TheeMattOliver** [comment]
Hi @jvdl! 👋 

App passwords are definitely working, and we're pushing tokens to Bitbucket but do you happen to know if there's a recommended Bitbucket Cloud API method to create a tree, similar to the [Github API](https://docs.github.com/en/rest/git/trees#create-a-tree)`createTree ` method (https://docs.github.com/en/rest/git/trees#create-a-tree) or [Gitlab/gitbeaker's ](https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Repositories.ts) `repositories.tree` method? 

The closest method I believe we do have is https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-post. I haven’t had time to tinker with that and try to make it work because I’m a bit oversubscribed at work but that's what we need to do to complete the round-trip.

Just thought I'd ask since you're an expert ;)

**Comment by jvdl** [comment]
Hiya @TheeMattOliver :)

I saw the PR and it's great that there's some very solid progress on this!

Depending on what you're trying to do of course, but I think you're right that the method you linked is probably the most appropriate for your use case to have the plugin upload the token file(s) and commit them as the new head of the given branch.

(Hardly an expert :P, but glad to be able to be of some help ;))

**Comment by coreyleelarson** [comment]
Any news on when this will be released? I see the PR has been merged.

Our client uses Bitbucket for all of their repos and it doesn't look like we'll be able to implement this plugin into our workflow without some sort of workaround until it includes Bitbucket support.

This plugin is exactly what our team is looking for, great work @six7 and all!

**Comment by TheeMattOliver** [comment]
Hey @coreyleelarson, thanks for this. I would love for this to be working fully.

The Bitbucket feature in Figma Tokens is currently behind a feature flag until we can traverse and recursively create a tree from the contents of the repo similar to [this method](https://docs.github.com/en/rest/git/trees#create-a-tree) or [this method](https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Repositories.ts).

The closest thing I think we have available is https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-post. Again, haven’t had time to tinker with that because I’m oversubscribed at work.

Atlassian should really make this endpoint a priority. This is [their public roadmap](https://trello.com/b/8XBuIeIu/atlassian-platform-for-developers-roadmap).

Repository mirroring is a non-ideal compromise workaround that would allow your client to get the benefits of Figma Tokens' two-way sync feature while storing tokens in Bitbucket and maintaining git history.

**Comment by wraybowling** [comment]
Lack of Bitbucket support has been a blocker for the company I work for. I dug in today to see what is going on. It looks like the #1159 "next" branch for release 135 #1551 is supposed to ship by January 25 according to the roadmap linked above. https://github.com/orgs/tokens-studio/projects/34/views/6?filterQuery=-is%3Aclosed+bitbucket The build looks like it's failing due to a few files lacking coverage. Never before seeing the token studio code, I'm not sure what to make of the files that lack coverage but I did try for an hour or two.

**Comment by erhankudretli** [comment]
> Hey @coreyleelarson, thanks for this. I would love for this to be working fully.
> 
> The Bitbucket feature in Figma Tokens is currently behind a feature flag until we can traverse and recursively create a tree from the contents of the repo similar to [this method](https://docs.github.com/en/rest/git/trees#create-a-tree) or [this method](https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Repositories.ts).
> 
> Atlassian should really make this endpoint a priority. This is [their public roadmap](https://trello.com/b/8XBuIeIu/atlassian-platform-for-developers-roadmap).
> 
> Repository mirroring is a non-ideal compromise workaround that would allow your client to get the benefits of Figma Tokens' two-way sync feature while storing tokens in Bitbucket and maintaining git history.



> Hi @jvdl! 👋
> 
> App passwords are definitely working, and we're pushing tokens to Bitbucket but do you happen to know if there's a recommended Bitbucket Cloud API method to create a tree, similar to the [Github API](https://docs.github.com/en/rest/git/trees#create-a-tree)`createTree ` method (https://docs.github.com/en/rest/git/trees#create-a-tree) or [Gitlab/gitbeaker's ](https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/Repositories.ts) `repositories.tree` method?
> 
> The closest method I believe we do have is https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-post. I haven’t had time to tinker with that and try to make it work because I’m a bit oversubscribed at work but that's what we need to do to complete the round-trip.
> 
> Just thought I'd ask since you're an expert ;)
Hi @TheeMattOliver , Can you please explain how you manage to use the app password to interact with Bitbucket please. 
I am not familiar with Figma/Tokens studio, I couldn`t sync 
Thank in advance :)

**Comment by wraybowling** [comment]
Hold my beer.

**Comment by dbuizert** [comment]
Has there been any update in regard to bitbucket support?

**Comment by SamIam4Hyma** [comment]
@six7 suggesting we close this one as the solution #2512 tackles this

**Comment by six7** [comment]
Yes. Closing this as this will be released in 2.0 - beta starting soon - reach out in Slack if you want to participate 🙏

**Comment by UdayHyma** [comment]
Added to Featurebase Roadmap- [](https://tokensstudio.featurebase.app/p/bitbucket-sync-provider-added)
