### ISSUE TITLE
Add x- and y-properties to Tokens

### ISSUE THREAD

**Issue by wolfXDnet** [tokens-studio/figma-plugin#682]
**Is your feature request related to a problem? Please describe.**
I'm working on a DesignSystem that will allow different densities (e.g. 'normal' using a spacing of 16 and 'condensed' with a spacing of 10) of the components. The density will be defined by a common base token that is referred extensively.
Some components use zero height and width frames to position content. Some elements inside those frames require a positive or negative x or y position to be placed correctly. This positioning is dependent on the base token as well.
Unfortunately x- and y-properties are, in contrast to width and height, not available in Figma Tokens.

**Describe the solution you'd like**
Extending sizing tokens by x- and y-properties would enable us to reposition nodes in line with density changes.

**Comment by D1no** [comment]
@six7 Need that too. I have screenshots where I need to position a mask. 

Lets say screenshot of a linkedin profile and you want to design and preview a new profile picture. I need to move the mask to the appropriate `x` / `y` position over the screenshot to mask out the existing profile image. Since linkedin makes continuously changes, you need to nudge the position of the mask here and there all the time you make a new screenshot.

Being able to do that via two token properties per devices type, was the reason to try tokens studio. But apparently: not available. Have to code something myself I guess 😑 _don't want to set-up complicated auto layouts just to position a mask_
